global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:9090']

  # - job_name: 'restaurant-service'
  #   static_configs:
  #     - targets: ['restaurant-service:9091']
